# åˆ†äº«å›¾æ ‡
ShowShareButtons: true
ShareButtons:
  ['linkedin', 'twitter', 'x', 'reddit', 'facebook', 'whatsapp', 'telegram', 'ycombinator']

# ç¤¾äº¤å›¾æ ‡
socialIcons:
  - name: github
    title: View Source on Github
    url: 'https://github.com/rickeygong'
  - name: linkedin
    title: Connect on LinkedIn
    url: 'https://linkedin.com/in/donghai-gong-11a74b225/'
  - name: email
    title: Send me an Email
    url: 'mailto:gdhblog@outlook.com'
  - name: instagram
    title: Follow on Instagram
    url: 'https://www.instagram.com/donghai_gong/'
  - name: rss
    title: Subscribe to RSS Feed
    url: '/index.xml'

# ä¸»é¡µä¸ªäººä¿¡æ¯
homeInfoParams:
  Title: 'Donghai'
  Content: >
    ðŸ‘‹ Welcome to my corner of the web. Here, I document the hurdles I hit in projects, the things that spark my curiosity, and the traces of where I've been â€” books, trips, and the people along the way.

# cover:
#     hidden: true # hide everywhere but not in structured data
#     hiddenInList: true # hide on list pages and home
#     hiddenInSingle: true # hide on single page

footer:
  moe:
    enable: true
    url: 'https://icp.gov.moe/?keyword=mgrowup.com'
  travellings:
    enable: true
    url: 'https://www.travellings.cn/go.html'
  foreverblog:
    enable: true
    url: 'https://www.foreverblog.cn/'
  blogsclub:
    enable: true
    url: 'https://www.blogsclub.org/blog/45.html'

comments:
  enabled: false
  system: 'giscus'
  giscus:
    repo: 'your-repo'
    repoId: 'your-repoId'
    categoryId: 'your-categoryId'
    category: 'Announcements'
    mapping: 'pathname'
    strict: '0'
    reactionsEnabled: '1'
    emitMetadata: '0'
    inputPosition: 'top'
    lang: 'zh-CN'

analytics:
  enabled: false
  umami:
    enabled: false
    websiteid: 'your-websiteid'
    src: 'https://cloud.umami.is/script.js'
    domains: 'your-domains'
    enableTrackEvent: true
    scriptName: ''
    dataDomains: ''
  clarity:
    enabled: false
    analytics: 'your-analytics'
  google:
    enabled: false
    id: 'your-id'
